version: "3"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_HOST: "https://${BACKEND_DOMAIN}"
    restart: always
    environment:
      VIRTUAL_HOST: "${FRONTEND_DOMAIN?:}"
      LETSENCRYPT_HOST: "${FRONTEND_DOMAIN}"
    networks:
      - default
      - nginx-proxy

  backend:
    build: ./backend
    restart: always
    environment:
      VIRTUAL_HOST: ${BACKEND_DOMAIN:?}
      LETSENCRYPT_HOST: ${BACKEND_DOMAIN}
    volumes:
      - ./backend/pb_data:/app/pb_data
      - ./backend/migrations:/app/migrations
    networks:
      - default
      - nginx-proxy

networks:
  default:
  nginx-proxy:
    external: true
