version: "3"

services:
  frontend:
    build:
      context: ./frontend
      args:
        # TODO: set to actual backend url when its deployed
        VITE_API_HOST: "http://localhost:3000"
    restart: always
    environment:
      VIRTUAL_HOST: "${FRONTEND_DOMAIN?:}"
      LETSENCRYPT_HOST: "${FRONTEND_DOMAIN}"
    networks:
      - default
      - nginx-proxy

networks:
  default:
  nginx-proxy:
    external: true
